"""
Input/output helpers for Evoscope simulation outputs.

This module provides CSV export functions for the regulatory summaries
generated by the Evoscope simulation. It writes global gene/protein dynamics
and cluster-level gene/protein dynamics in tabular form, allowing downstream
plotting, aggregation, correlation analysis, and autoencoder-based modeling.

Main outputs
------------
global_genes.csv
    Mean global expression values over simulation steps.

cluster_genes.csv
    Cluster-specific expression values and cluster sizes over simulation
    steps.


Evoscope — minimal regulatory spatial model for emergent multicellular organization.

Author: Luca Zammataro
Organization: Lunan Foldomics LLC
"""

from .enums import CommitmentState
from pathlib import Path
import csv


def _resolve_output_path(path, outdir=None):
    """Resolve an output file path, optionally inside an output directory."""
    path = Path(path)

    if outdir is not None:
        outdir = Path(outdir)
        outdir.mkdir(parents=True, exist_ok=True)
        path = outdir / path.name
    else:
        path.parent.mkdir(parents=True, exist_ok=True)

    return path


def save_global_gene_csv(sim, path="global_genes.csv", outdir=None):
    """Export system-level gene/protein histories."""

    output_path = _resolve_output_path(path, outdir=outdir)

    genes = list(sim.gene_history.keys())
    if not genes:
        return output_path

    steps = len(sim.gene_history[genes[0]])

    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["step"] + genes)

        for i in range(steps):
            row = [i] + [sim.gene_history[g][i] for g in genes]
            writer.writerow(row)

    return output_path


def save_cluster_gene_csv(sim, path="cluster_genes.csv", outdir=None):
    """Export cluster-resolved gene/protein histories."""

    output_path = _resolve_output_path(path, outdir=outdir)

    genes = ["T1", "T2", "I", "R", "M", "K", "S"]

    if not hasattr(sim, "cluster_gene_history") or not sim.cluster_gene_history:
        return output_path

    steps = len(sim.cluster_gene_history[0][genes[0]])

    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        header = ["step", "cluster", "size"] + genes
        writer.writerow(header)

        for i in range(steps):
            for cid in range(8):
                row = [i, cid, sim.cluster_size_history[cid][i]]
                for g in genes:
                    row.append(sim.cluster_gene_history[cid][g][i])
                writer.writerow(row)

    return output_path


def save_population_metrics_csv(sim, path="population_metrics.csv", outdir=None):
    """Export population-level covariates for representation-learning controls.

    This file supports interpretation of latent trajectories by recording simple
    demographic, occupancy, and cluster-composition variables over time. It does
    not alter the simulation dynamics and is not used as an autoencoder target.
    """

    output_path = _resolve_output_path(path, outdir=outdir)

    genes = list(sim.gene_history.keys())
    if not genes:
        return output_path

    steps = len(sim.gene_history[genes[0]])
    lattice_sites = sim.cfg.width * sim.cfg.height

    header = [
        "step",
        "total_cells",
        "empty_sites",
        "occupied_density",
        "committed_cells",
        "committed_density",
        "undetermined_cells",
        "undetermined_density",
        "decommitted_cells",
        "decommitted_density",
        "uncommitted_cells",
        "uncommitted_density",
        "n_clusters_present",
        "largest_cluster",
    ] + [f"cluster_{cid}_size" for cid in range(8)]

    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)

        for i in range(steps):
            cluster_sizes = [
                sim.cluster_size_history[cid][i]
                for cid in range(8)
            ]

            committed_cells = sum(cluster_sizes)

            if i < len(sim.metrics_history):
                metrics = sim.metrics_history[i]
                total_cells = int(metrics.get("alive", committed_cells))
                undetermined_cells = int(metrics.get("undetermined", 0))
                decommitted_cells = int(metrics.get("decommitted", 0))
                n_clusters_present = int(
                    metrics.get(
                        "n_clusters_present",
                        sum(1 for s in cluster_sizes if s > 0),
                    )
                )
                largest_cluster = int(
                    metrics.get(
                        "largest_cluster",
                        max(cluster_sizes) if cluster_sizes else 0,
                    )
                )
            else:
                total_cells = committed_cells
                undetermined_cells = 0
                decommitted_cells = 0
                n_clusters_present = sum(1 for s in cluster_sizes if s > 0)
                largest_cluster = max(cluster_sizes) if cluster_sizes else 0

            empty_sites = lattice_sites - total_cells
            uncommitted_cells = total_cells - committed_cells

            occupied_density = total_cells / lattice_sites if lattice_sites else 0.0
            committed_density = committed_cells / lattice_sites if lattice_sites else 0.0
            undetermined_density = undetermined_cells / lattice_sites if lattice_sites else 0.0
            decommitted_density = decommitted_cells / lattice_sites if lattice_sites else 0.0
            uncommitted_density = uncommitted_cells / lattice_sites if lattice_sites else 0.0

            row = [
                i,
                total_cells,
                empty_sites,
                occupied_density,
                committed_cells,
                committed_density,
                undetermined_cells,
                undetermined_density,
                decommitted_cells,
                decommitted_density,
                uncommitted_cells,
                uncommitted_density,
                n_clusters_present,
                largest_cluster,
            ] + cluster_sizes

            writer.writerow(row)

    return output_path

